comment:
  on-update: edit

  header: |
    Contract sizes

  footer: |
    ---
    This is an automated comment :robot:.

  snippets:
    - id: any-source-file-changed
      files:
        - "src/**/*.sol"
      body: |
        ```
        {{ content }}
        ```
