[lintspec]
paths = ["src"]
exclude = [
    "src/OracleMiddleware/mock",
    "src/Usdn/Usdn.sol",
    "src/UsdnProtocol/libraries",
    "src/utils/Wusdn4626.sol",
]
notice_or_dev = true

[enum]
param = "required"

[struct]
param = "required"

[variable.public]
return = "ignored"
