paths = ["src"]
exclude = [
    "src/OracleMiddleware/mock",
    "src/Usdn/Usdn.sol",
    "src/UsdnProtocol/libraries",
]
constructor = true
struct_params = true
enum_params = true
enforce_all = true
