# ---------------------------------------------------------------------------- #
#                                Default profile                               #
# ---------------------------------------------------------------------------- #

[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
libs = ["node_modules", "dependencies"]
gas_reports = ["*"]
ffi = true
ast = true
build_info = true
show_progress = true
extra_output = ["storageLayout"]
ignored_error_codes = [
    "code-size",
    "init-code-size",
    "license",
    "too-many-warnings",
    "transient-storage",
]

# -------------------------------- Remappings -------------------------------- #

remappings = [
    "@chainlink/=dependencies/@chainlink-1.2.0/",
    "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.1.0/",
    "@pythnetwork/pyth-sdk-solidity/=dependencies/@pythnetwork-pyth-sdk-solidity-3.1.0/",
    "@redstone-finance/evm-connector/=dependencies/@redstone-finance-evm-connector-0.6.2/",
    "@smardex-dex-contracts/=dependencies/@smardex-dex-contracts-1.0.1/",
    "@smardex-solidity-libraries-1/=dependencies/@smardex-solidity-libraries-1.0.1/src/",
    "@uniswap/permit2/=dependencies/@uniswap-permit2-1.0.0/",
    "@uniswapV3=dependencies/@uniswap-v3-core-1.0.2-solc-0.8-simulate/",
    "forge-std/=dependencies/forge-std-1.9.4/src/",
    "openzeppelin-foundry-upgrades/=dependencies/openzeppelin-foundry-upgrades-0.3.6/src/",
    "solady/src/=dependencies/solady-0.0.228/src/",
]

# ---------------------------------- Format ---------------------------------- #

[profile.default.fmt]
line_length = 120
bracket_spacing = true
wrap_comments = true
number_underscore = "thousands"
sort_imports = true

# ---------------------------------- Fuzzing --------------------------------- #

[profile.default.fuzz]
fail_on_revert = true

[profile.default.invariant]
corpus_dir = ".corpus"
shrink_run_limit = 50_000
fail_on_revert = true

# ---------------------------------------------------------------------------- #
#                                 Local profile                                #
# ---------------------------------------------------------------------------- #

# ---------------------------------- Fuzzing --------------------------------- #

[profile.local.fuzz]
runs = 10_000

[profile.local.invariant]
runs = 10_000
depth = 15

# ---------------------------------------------------------------------------- #
#                             Heavy fuzzing profile                            #
# ---------------------------------------------------------------------------- #

# ---------------------------------- Fuzzing --------------------------------- #

[profile.heavy_fuzzing.fuzz]
runs = 1_000_000

[profile.heavy_fuzzing.invariant]
runs = 100_000
depth = 100

# ---------------------------------------------------------------------------- #
#                                  CI profile                                  #
# ---------------------------------------------------------------------------- #

[profile.ci]
verbosity = 3
ffi = false
show_progress = false

# ---------------------------------- Fuzzing --------------------------------- #

[profile.ci.fuzz]
runs = 256

[profile.ci.invariant]
runs = 256
depth = 5

# ---------------------------------------------------------------------------- #
#                              Complete CI profile                             #
# ---------------------------------------------------------------------------- #

[profile.heavy_ci]
verbosity = 3
ffi = true
show_progress = false

# ---------------------------------- Fuzzing --------------------------------- #

[profile.heavy_ci.fuzz]
runs = 1024

[profile.heavy_ci.invariant]
runs = 1024
depth = 50

# ---------------------------------------------------------------------------- #
#                                  Deployments                                 #
# ---------------------------------------------------------------------------- #

[rpc_endpoints]
mainnet = "${URL_ETH_MAINNET}"
sepolia = "${URL_SEPOLIA}"
anvil = "${URL_ANVIL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# ---------------------------------------------------------------------------- #
#                                 Dependencies                                 #
# ---------------------------------------------------------------------------- #

[soldeer]
remappings_generate = true
remappings_location = "config"
remappings_version = true

[dependencies]
"@chainlink" = { version = "1.2.0", url = "https://github.com/smartcontractkit/chainlink/archive/c3dc764bba9e1c57b3f7933bcb804a1740fab695.zip" }
"@openzeppelin-contracts-upgradeable" = "5"
"@openzeppelin-contracts" = "5"
"@pythnetwork-pyth-sdk-solidity" = "3"
"@redstone-finance-evm-connector" = "0.6"
"@uniswap-permit2" = { version = "1.0.0", url = "https://github.com/Uniswap/permit2/archive/cc56ad0f3439c502c246fc5cfcc3db92bb8b7219.zip" }
forge-std = "1"
openzeppelin-foundry-upgrades = "0.3"
solady = "0.0.228"
"@smardex-solidity-libraries" = "1"
"@uniswap-v3-core" = "1.0.2-solc-0.8-simulate"
"@smardex-dex-contracts" = "1.0.1"
