# ---------------------------------------------------------------------------- #
#                                Default profile                               #
# ---------------------------------------------------------------------------- #

# --------------------------------- Compiler --------------------------------- #

[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 20_000
libs = ["node_modules", "dependencies"]
invariant = { fail_on_revert = true }
gas_reports = ["*"]
ignored_error_codes = [
    "license",
    "code-size",
    "init-code-size",
    "transient-storage",
    "too-many-warnings",
]

# -------------------------------- Remappings -------------------------------- #


remappings = [
    "@chainlink/=node_modules/@chainlink/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.0.2/",
    "@pythnetwork/pyth-sdk-solidity/=dependencies/@pythnetwork-pyth-sdk-solidity-3.1.0/",
    "@redstone-finance/evm-connector/=dependencies/@redstone-finance-evm-connector-0.6.1/",
    "@uniswap/permit2/=node_modules/@uniswap/permit2/",
    "forge-std/=dependencies/forge-std-1.9.1/src/",
    "solady/src/=dependencies/solady-0.0.228/src/",
]

# ---------------------------------- Format ---------------------------------- #

[profile.default.fmt]
line_length = 120
bracket_spacing = true
wrap_comments = true
number_underscore = "thousands"
sort_imports = true

# ---------------------------------------------------------------------------- #
#                                 Local profile                                #
# ---------------------------------------------------------------------------- #

[profile.local]
ffi = true

# ---------------------------------- Fuzzing --------------------------------- #

[profile.local.fuzz]
runs = 10_000

[profile.local.invariant]
runs = 10_000
depth = 15
# call_override = true # makes invariant tests hang
dictionary_weight = 80

# ---------------------------------------------------------------------------- #
#                             Heavy fuzzing profile                            #
# ---------------------------------------------------------------------------- #

[profile.heavy_fuzzing]
ffi = true

# ---------------------------------- Fuzzing --------------------------------- #

[profile.heavy_fuzzing.fuzz]
runs = 1_000_000

[profile.heavy_fuzzing.invariant]
runs = 1_000_000
depth = 30
# call_override = true
dictionary_weight = 80

# ---------------------------------------------------------------------------- #
#                                  CI profile                                  #
# ---------------------------------------------------------------------------- #

[profile.ci]
verbosity = 3

# ---------------------------------- Fuzzing --------------------------------- #

[profile.ci.fuzz]
runs = 256

[profile.ci.invariant]
runs = 256
depth = 5
# call_override = false
dictionary_weight = 40

# ---------------------------------------------------------------------------- #
#                              Complete CI profile                             #
# ---------------------------------------------------------------------------- #

[profile.heavy_ci]
verbosity = 3
ffi = true

# ---------------------------------- Fuzzing --------------------------------- #

[profile.heavy_ci.fuzz]
runs = 1024

[profile.heavy_ci.invariant]
runs = 1024
depth = 10
dictionary_weight = 60

# ---------------------------------------------------------------------------- #
#                                  Deployments                                 #
# ---------------------------------------------------------------------------- #

[rpc_endpoints]
mainnet = "${URL_ETH_MAINNET}"
sepolia = "${URL_SEPOLIA}"
anvil = "${URL_ANVIL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[dependencies]
"@uniswap/permit2" = { version = "1.0.0", git = "https://github.com/Uniswap/permit2.git", rev = "cc56ad0f3439c502c246fc5cfcc3db92bb8b7219" }
forge-std = "1.9.1"
"@openzeppelin-contracts" = "5.0.2"
"@pythnetwork-pyth-sdk-solidity" = "3.1.0"
"@redstone-finance-evm-connector" = "0.6.1"
solady = "0.0.228"
