[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-primitives = "0.4"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
decimal-rs = "0.1"
