name: Main workflow
on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci && forge soldeer install

      # skip for now
      #- name: Check gas snapshots
      #  run: npm run snapshot:check

      - name: Run tests
        run: forge test --no-match-test "(FFI|Fork)" --no-match-contract Fork

  notify-on-failure:
    needs: [run-ci]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    uses: ./.github/workflows/notify_failure.yml
    secrets: inherit
