name: find_secrets

on: pull_request

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.79.0
        with:
          base: ${{ github.event.repository.default_branch }}=
          extra_args: --debug --only-verified
