name: Natspec report
on:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  natspec-smells:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      total-smells: ${{ steps.natspec-smells-action.outputs.total-smells }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci && forge soldeer install

      - name: Remove unused remappings file
        run: rm -f remappings.txt

      - name: Report natspec smells findings
        id: natspec-smells-action
        uses: SmarDex-Ecosystem/natspec-smells-action@v2
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          working-directory: ./
          update-comment: true

      - name: Fail on findings
        if: ${{ steps.natspec-smells-action.outputs.total-smells > 0 }}
        run: exit 1

  notify-on-failure:
    needs: natspec-smells
    if: ${{ always() && needs.natspec-smells.outputs.total-smells > 0 }}
    uses: ./.github/workflows/notify_failure.yml
    secrets: inherit